import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar";
import Footer from "./_components/footer";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import prisma from "@/lib/prisma";
import UserNotVerified from "./_components/user-not-verified";
import "@mantine/charts/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  let dbUser = null;

  if (user) {
    dbUser = await prisma.user.findUnique({
      where: {
        id: user.id,
      },
    });
    // console.log(user.id, dbUser);
  }
  const isVerified =
    user === null ||
    dbUser === null ||
    (user && dbUser && dbUser.role !== "NOT_VERIFIED");

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="relative">
        <Providers>
          {/* <DndProvider backend={HTML5Backend}> */}
          <MantineProvider
            defaultColorScheme="light"
            cssVariablesSelector="html"
          >
            {!isVerified && (
              <>
                <UserNotVerified />
              </>
            )}
            {isVerified && (
              <>
                <div className="h-24"></div>
                <Navbar />
                {/* <div className="absolute -z-10 h-full w-full bg-white bg-grid-gray-300/[0.2]"></div> */}

                <main
                  className="min-h-screen
              "
                >
                  {children}
                </main>
                <Footer />
              </>
            )}
          </MantineProvider>
          {/* </DndProvider> */}
        </Providers>
      </body>
    </html>
  );
}
